version: '3.3'

services:
    nginx:
        image: 'nginx:latest'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/app
        ports:
          - 8080:8080

    php:
        build: .
        volumes:
            - ./:/app

    mysql:
        image: 'mysql:latest'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - db-data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=lara
        ports:
          - '3306:3306'


    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'

volumes:
    db-data:
